
language: node_js
node_js:
  - "0.10"
 
before_install:
  - "node --version"
  - "npm --version"

install:
  # Install meteor
  - "curl https://install.meteor.com | /bin/sh"
  # Install spacejam
  - "npm install -g spacejam"

before_script:
  - "meteor --version"
  - "phantomjs -v"
  - "spacejam package-version"
  - "ls -al ./"
 
script:
  - "spacejam test-packages ./"

