
language: node_js
node_js:
  - "0.10"
 
install:
  # Install meteor
  - "curl https://install.meteor.com | /bin/sh"
  # no sudo, so, no meteor in path, let's update our path
  - "export PATH=$PATH:$HOME/.meteor"
  # Install spacejam
  - "npm install -g spacejam"

before_script:
  - "meteor --version"
  - "phantomjs -v"
  - "spacejam package-version"
  - "ls -al ./"
 
script:
  - "spacejam test-packages ./"

